package com.music.bitchord.alarm
import org.junit.Assert.*
import org.junit.Test
class AlarmStateMachineTest{
 private val song=AlarmSong("v","Song","Artist")
 private fun alarm(id:String,order:Long=1,repeat:Set<Int> = setOf(1))=AlarmConfig(id,order,enabled=true,hour=7,song=song,repeatDays=repeat,generation=2)
 @Test fun `editing A invalidates only A and keeps B unchanged`() {val a=AlarmStateMachine.scheduled(alarm("a").copy(snoozeEpochMillis=300,snoozeToken="old-snooze"),100,AlarmScheduleMode.EXACT);val b=AlarmStateMachine.scheduled(alarm("b"),200,AlarmScheduleMode.EXACT);val changed=AlarmStateMachine.edit(a,a.copy(hour=8));assertNull(changed.scheduledToken);assertNull(changed.snoozeToken);assertEquals(3,changed.generation);assertEquals(200L,b.scheduledEpochMillis)}
 @Test fun `disabling A leaves enabled B unchanged`() {val a=alarm("a");val b=alarm("b");val updated=listOf(a,b).map{if(it.id=="a")AlarmStateMachine.edit(it,it.copy(enabled=false))else it};assertFalse(updated.first{it.id=="a"}.enabled);assertEquals(b,updated.first{it.id=="b"})}
 @Test fun `stale occurrence cannot trigger after edit`() {val old=AlarmStateMachine.scheduled(alarm("a"),100,AlarmScheduleMode.EXACT);val edited=AlarmStateMachine.edit(old,old.copy(hour=8));assertNull(AlarmStateMachine.trigger(AlarmCollection(alarms=listOf(edited)),"a",requireNotNull(old.scheduledToken),100,100,false))}
 @Test fun `stale snooze occurrence cannot trigger after edit`() {val old=alarm("a").copy(snoozeEpochMillis=300,snoozeToken="old-snooze");val edited=AlarmStateMachine.edit(old,old.copy(hour=8));assertNull(AlarmStateMachine.trigger(AlarmCollection(alarms=listOf(edited)),"a","old-snooze",300,300,true))}
 @Test fun `stop returns captured alarm volume and rejects stale action`() {val state=AlarmCollection(alarms=listOf(alarm("a")),activeSession=AlarmSession("a","active",999,4));assertNull(AlarmStateMachine.end(state,"a","stale"));val ended=requireNotNull(AlarmStateMachine.end(state,"a","active"));assertEquals(4,ended.previousAlarmVolume);assertNull(ended.collection.activeSession)}
 @Test fun `snooze A leaves B and base recurrence untouched`() {val a=alarm("a");val b=alarm("b");val active=AlarmCollection(alarms=listOf(a,b),activeSession=AlarmSession("a","t",999,4));val snoozed=requireNotNull(AlarmStateMachine.snooze(active,"a","t",1_000));assertEquals(b,snoozed.collection.alarms[1]);assertEquals(a.repeatDays,snoozed.collection.alarms[0].repeatDays);assertEquals(601_000L,snoozed.epochMillis);assertEquals(4,snoozed.previousAlarmVolume);assertNull(snoozed.collection.activeSession)}
 @Test fun `new valid trigger replaces older active session deterministically`() {val a=AlarmStateMachine.scheduled(alarm("a"),100,AlarmScheduleMode.EXACT);val b=AlarmStateMachine.scheduled(alarm("b"),200,AlarmScheduleMode.EXACT);val old=AlarmSession("a","old",999,5);val transition=requireNotNull(AlarmStateMachine.trigger(AlarmCollection(alarms=listOf(a,b),activeSession=old),"b",requireNotNull(b.scheduledToken),200,200,false));assertEquals(old,transition.replaced);assertEquals("b",transition.collection.activeSession?.alarmId)}
 @Test fun `one shot A does not disable recurring B`() {val a=AlarmStateMachine.scheduled(alarm("a",repeat=emptySet()),100,AlarmScheduleMode.EXACT);val b=alarm("b");val result=requireNotNull(AlarmStateMachine.trigger(AlarmCollection(alarms=listOf(a,b)),"a",requireNotNull(a.scheduledToken),100,100,false));assertFalse(result.collection.alarms[0].enabled);assertTrue(result.collection.alarms[1].enabled)}
 @Test fun `sorting is chronological and stable for equal times`() {val values=listOf(alarm("c",3).copy(hour=9),alarm("b",2),alarm("a",1));assertEquals(listOf("a","b","c"),AlarmStateMachine.sorted(values).map{it.id})}
 @Test fun `pending identities isolate alarms and action kinds`() {assertNotEquals(alarmPendingIdentity("a","trigger"),alarmPendingIdentity("b","trigger"));assertNotEquals(alarmPendingIdentity("a","trigger"),alarmPendingIdentity("a","snooze-trigger"))}
 @Test fun `deleting A leaves B intact`() {val b=alarm("b");assertEquals(listOf(b),AlarmStateMachine.remove(AlarmCollection(alarms=listOf(alarm("a"),b)),"a").alarms)}
 @Test fun `reboot candidates include all enabled alarms only`() {val enabledA=alarm("a");val enabledB=alarm("b");val disabled=alarm("c").copy(enabled=false);assertEquals(listOf(enabledA,enabledB),AlarmStateMachine.rescheduleCandidates(listOf(enabledA,disabled,enabledB)))}
 @Test fun `new alarms retain distinct supplied stable identities`() {val a=AlarmStateMachine.newAlarm("uuid-a",1);val b=AlarmStateMachine.newAlarm("uuid-b",2);assertEquals("uuid-a",a.id);assertEquals("uuid-b",b.id);assertNotEquals(a.id,b.id)}
 @Test fun `enabling A leaves disabled B unchanged`() {val a=alarm("a").copy(enabled=false);val b=alarm("b").copy(enabled=false);val updated=listOf(a,b).map{if(it.id=="a")AlarmStateMachine.edit(it,it.copy(enabled=true))else it};assertTrue(updated.first{it.id=="a"}.enabled);assertEquals(b,updated.first{it.id=="b"})}
}
