<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <UseWinUI>true</UseWinUI>
    <WindowsPackageType>MSIX</WindowsPackageType>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <SelfContained>true</SelfContained>
    <EnableMsixTooling>true</EnableMsixTooling>
    <EnableDefaultPageItems>false</EnableDefaultPageItems>
    <Nullable>enable</Nullable>
    <RootNamespace>BitChord.WinUI</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <Platforms>x86;x64;ARM64</Platforms>
    <EnablePreviewMsixTooling>true</EnablePreviewMsixTooling>
    <UseRidGraph>true</UseRidGraph>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.6.250205002" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.3916" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\Logo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="Assets\Logo44.png" />
    <Content Include="Assets\Logo50.png" />
    <Content Include="Assets\Logo150.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Pages\**\*.cs" />
  </ItemGroup>
</Project>
