package com.music.bitchord.desktop

import kotlin.test.Test
import kotlin.test.assertEquals

/** The names the lyrics databases are asked for. */
class DesktopLyricsQueryTest {

    @Test
    fun featuredCreditsComeOff() {
        assertEquals("Dracula", "Dracula (feat. JENNIE)".forLyricsSearch())
        assertEquals("Dracula", "Dracula [ft. JENNIE]".forLyricsSearch())
        assertEquals("Dracula", "Dracula (with JENNIE)".forLyricsSearch())
        assertEquals("Dracula", "Dracula feat. JENNIE".forLyricsSearch())
    }

    @Test
    fun uploadLabellingComesOff() {
        assertEquals("Blinding Lights", "Blinding Lights (Official Video)".forLyricsSearch())
        assertEquals("Blinding Lights", "Blinding Lights [Official Music Video]".forLyricsSearch())
        assertEquals("Blinding Lights", "Blinding Lights (Lyrics)".forLyricsSearch())
        assertEquals("Blinding Lights", "Blinding Lights (4K)".forLyricsSearch())
    }

    @Test
    fun aBracketNamingAnotherRecordingStays() {
        // Each of these is a different take with different words in places.
        listOf(
            "Heat Waves (Remix)",
            "Heat Waves (Acoustic)",
            "Heat Waves (Live)",
            "Heat Waves (Remastered 2011)",
            "Heat Waves (Sped Up)",
        ).forEach { assertEquals(it, it.forLyricsSearch()) }
    }

    @Test
    fun aTitleThatWasOnlyPackagingKeepsWhatWeWereGiven() {
        // Better to ask with a bad name than with no name at all.
        assertEquals("(Official Video)", "(Official Video)".forLyricsSearch())
    }

    @Test
    fun autoGeneratedChannelNamesLoseTheirSuffix() {
        assertEquals("Tame Impala", "Tame Impala - Topic".artistForLyricsSearch())
        assertEquals("Tame Impala", "Tame Impala".artistForLyricsSearch())
    }
}
